import turtle
import random

# sets background
bg = turtle.Screen()
bg.bgcolor("White")

# Line 1
turtle.color('Blue')
turtle.penup()
turtle.goto(0, 170)
style = ('Courier', 30, 'italic')
turtle.write('Good luck', font=style, align='center')
turtle.hideturtle()

turtle.color('Blue')
turtle.penup()
turtle.goto(0, 130)
style = ('Courier', 30, 'italic')
turtle.write('at college!', font=style, align='center')
turtle.hideturtle()

turtle.color('Black')
turtle.penup()
turtle.goto(31, -190)
turtle.pendown()
turtle.forward(45)
turtle.hideturtle()

turtle.color('Black')
turtle.penup()
turtle.goto(76, -190)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(76, -181)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(85, -181)
turtle.pendown()
turtle.left(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.goto(85, -163)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(76, -163)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(76, -154)
turtle.pendown()
turtle.left(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.goto(58, -154)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(58, -145)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(67, -145)
turtle.pendown()
turtle.left(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.goto(67, -127)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(58, -127)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(58, -118)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(67, -118)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(67, -109)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(76, -109)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(76, -100)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(85, -100)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(85, -91)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(94, -91)
turtle.pendown()
turtle.left(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.goto(94, -64)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(85, -64)
turtle.pendown()
turtle.right(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.goto(85, -46)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(76, -46)
turtle.pendown()
turtle.right(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.goto(76, -28)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(67, -28)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(67, -19)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(58, -19)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(58, -10)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(67, -10)
turtle.pendown()
turtle.left(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.goto(67, 17)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(58, 17)
turtle.pendown()
turtle.right(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.goto(58, 35)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(67, 35)
turtle.pendown()
turtle.left(90)
turtle.forward(36)

turtle.color('Black')
turtle.penup()
turtle.goto(67, 71)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(58, 71)
turtle.pendown()
turtle.right(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.goto(58, 89)
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(49, 89)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(49, 98)
turtle.pendown()
turtle.left(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.goto(31, 98)
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.goto(31, 107)
turtle.pendown()
turtle.left(90)
turtle.forward(90)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(36)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(45)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.begin_fill()
turtle.penup()
turtle.goto(40, 35)
turtle.pendown()
turtle.right(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(27)
turtle.end_fill()


turtle.color('Black')
turtle.begin_fill()
turtle.penup()
turtle.goto(-41, 35)
turtle.pendown()
turtle.right(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)
turtle.end_fill()

turtle.color('Black')
turtle.begin_fill()
turtle.penup()
turtle.goto(-28, 26)
turtle.pendown()
turtle.left(90)
turtle.forward(27)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)
turtle.end_fill()

turtle.color('Black')
turtle.begin_fill()
turtle.penup()
turtle.goto(45, 16)
turtle.pendown()
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(82)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(18)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(100)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.left(90)
turtle.forward(9)

turtle.color('Black')
turtle.penup()
turtle.pendown()
turtle.right(90)
turtle.forward(9)
turtle.end_fill()
